### ISSUE TITLE
Tachiyomi extension broken

### ISSUE THREAD

**Issue by etcpackage** [rs1703/koushoku#3]
title, I can't see or download images

**Comment by rs1703** [comment]
The website is now serving images from subdomains (*.domain.com) instead of directly. I have already pushed a PR to fix this issue but still pending, at this point you should just compile the extension at your own if you don't want to wait.

**Comment by rs1703** [comment]
I'll just redirect the old paths to the new ones, so it should be working for now. It's only a temporary workaround until the PR get accepted.

**Comment by etcpackage** [comment]
> I'll just redirect the old paths to the new ones, so it should be working for now. It's only a temporary workaround until the PR get accepted.

still can't see images but thank you I will use the browser until fix
